cp -r template MgOn00 && cd MgOn00 && pwd && cp ../posinps/MgOn00_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn01 && cd MgOn01 && pwd && cp ../posinps/MgOn01_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn02 && cd MgOn02 && pwd && cp ../posinps/MgOn02_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn03 && cd MgOn03 && pwd && cp ../posinps/MgOn03_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn04 && cd MgOn04 && pwd && cp ../posinps/MgOn04_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn05 && cd MgOn05 && pwd && cp ../posinps/MgOn05_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn06 && cd MgOn06 && pwd && cp ../posinps/MgOn06_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn07 && cd MgOn07 && pwd && cp ../posinps/MgOn07_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn08 && cd MgOn08 && pwd && cp ../posinps/MgOn08_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn09 && cd MgOn09 && pwd && cp ../posinps/MgOn09_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn10 && cd MgOn10 && pwd && cp ../posinps/MgOn10_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn11 && cd MgOn11 && pwd && cp ../posinps/MgOn11_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn12 && cd MgOn12 && pwd && cp ../posinps/MgOn12_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn13 && cd MgOn13 && pwd && cp ../posinps/MgOn13_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn14 && cd MgOn14 && pwd && cp ../posinps/MgOn14_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn15 && cd MgOn15 && pwd && cp ../posinps/MgOn15_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn16 && cd MgOn16 && pwd && cp ../posinps/MgOn16_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn17 && cd MgOn17 && pwd && cp ../posinps/MgOn17_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn18 && cd MgOn18 && pwd && cp ../posinps/MgOn18_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn19 && cd MgOn19 && pwd && cp ../posinps/MgOn19_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOn20 && cd MgOn20 && pwd && cp ../posinps/MgOn20_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp01 && cd MgOp01 && pwd && cp ../posinps/MgOp01_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp02 && cd MgOp02 && pwd && cp ../posinps/MgOp02_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp03 && cd MgOp03 && pwd && cp ../posinps/MgOp03_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp04 && cd MgOp04 && pwd && cp ../posinps/MgOp04_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp05 && cd MgOp05 && pwd && cp ../posinps/MgOp05_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp06 && cd MgOp06 && pwd && cp ../posinps/MgOp06_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp07 && cd MgOp07 && pwd && cp ../posinps/MgOp07_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp08 && cd MgOp08 && pwd && cp ../posinps/MgOp08_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp09 && cd MgOp09 && pwd && cp ../posinps/MgOp09_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp10 && cd MgOp10 && pwd && cp ../posinps/MgOp10_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp11 && cd MgOp11 && pwd && cp ../posinps/MgOp11_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp12 && cd MgOp12 && pwd && cp ../posinps/MgOp12_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp13 && cd MgOp13 && pwd && cp ../posinps/MgOp13_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp14 && cd MgOp14 && pwd && cp ../posinps/MgOp14_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp15 && cd MgOp15 && pwd && cp ../posinps/MgOp15_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp16 && cd MgOp16 && pwd && cp ../posinps/MgOp16_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp17 && cd MgOp17 && pwd && cp ../posinps/MgOp17_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp18 && cd MgOp18 && pwd && cp ../posinps/MgOp18_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp19 && cd MgOp19 && pwd && cp ../posinps/MgOp19_pos.rzx posinp.rzx && run.sh && cd ..
cp -r template MgOp20 && cd MgOp20 && pwd && cp ../posinps/MgOp20_pos.rzx posinp.rzx && run.sh && cd ..
